// Shared master casino list used by both the user tracker and the admin workspace.
// Keep this in sync with any casinos that should exist by default across all profiles.

export const casinoDirectory = [
  "Coinsback",
  "High 5 Casino",
  "ReBet",
  "Lucky Bunny",
  "Pulszbingo",
  "1UP",
  "Lucklake",
  "Punt",
  "Chanced",
  "SidePot",
  "MyPrize",
  "Lonestar",
  "RealPrize",
  "KingPrize",
  "Sheesh Casino",
  "Pulsz",
  "Sportzino",
  "Modo",
  "PlayFame",
  "YayCasino",
  "McLuck",
  "Hello Millions",
  "Megabonanza",
  "Jackpota",
  "Superboo",
  "Ace",
  "Spree",
  "The Win Zone",
  "Dogg House",
  "Lucky Bits Vegas",
  "Oder Casino",
  "WOW Vegas",
  "Fliff",
  "Coin Wizard",
  "Golden Hearts Games",
  "Rolling Riches",
  "Casino.click",
  "American Luck",
  "Luck Party",
  "NewLuck",
  "Shuffle.us",
  "Fortune Purple",
  "Fortune Wins",
  "AceBet",
  "Stake",
  "ThrillCoins",
  "SweepstakesCasino.com",
  "BangCoins",
  "DimeSweeps",
  "SweepsRoyal",
];

export const casinoDirectoryUrls: Record<string, string> = {
  Coinsback: "https://coinsback.com",
  "High 5 Casino": "https://high5casino.com",
  ReBet: "https://rebet.com",
  "Lucky Bunny": "https://luckybunnycasino.com",
  Pulszbingo: "https://pulszbingo.com",
  "1UP": "https://1upcasino.com",
  Lucklake: "https://lucklake.com",
  Punt: "https://punt.com",
  Chanced: "https://chanced.com",
  SidePot: "https://sidepot.com",
  MyPrize: "https://myprize.us",
  Lonestar: "https://lonestarcasino.com",
  RealPrize: "https://realprize.com",
  KingPrize: "https://kingprize.com",
  "Sheesh Casino": "https://sheesh.com",
  Pulsz: "https://pulsz.com",
  Sportzino: "https://sportzino.com",
  Modo: "https://modo.us",
  PlayFame: "https://playfame.com",
  YayCasino: "https://yaycasino.com",
  McLuck: "https://mcluck.com",
  "Hello Millions": "https://hellomillions.com",
  Megabonanza: "https://megabonanza.com",
  Jackpota: "https://jackpota.com",
  Superboo: "https://superboo.com",
  Ace: "https://ace.bet",
  Spree: "https://spree.com",
  "The Win Zone": "https://thewinzone.com",
  "Dogg House": "https://dogghouse.com",
  "Lucky Bits Vegas": "https://luckybitsvegas.com",
  "Oder Casino": "https://odercasino.com",
  "WOW Vegas": "https://wowvegas.com",
  Fliff: "https://fliff.com",
  "Coin Wizard": "https://coinwizard.com",
  "Golden Hearts Games": "https://goldenheartsgames.com",
  "Rolling Riches": "https://rollingriches.com",
  "Casino.click": "https://casino.click",
  "American Luck": "https://americanluck.com",
  "Luck Party": "https://luckparty.com",
  NewLuck: "https://newluck.com",
  "Shuffle.us": "https://shuffle.us",
  "Fortune Purple": "https://fortunepurple.com",
  "Fortune Wins": "https://fortunewins.com",
  AceBet: "https://acebet.com",
  Stake: "https://stake.us",
  ThrillCoins: "https://thrillcoins.com",
  "SweepstakesCasino.com": "https://sweepstakescasino.com",
  BangCoins: "https://bangcoins.com",
  DimeSweeps: "https://dimesweeps.com",
  SweepsRoyal: "https://sweepsroyal.com",
};
