import type { Casino } from "@/types/casino";

export interface PendingCasinoData {
  name: string;
  slug: string;
  siteUrl: string;
  dailyBonus: string;
  dailyBonusSc: string;
  dailyScAmount: number;
  minRedemption: string;
  intervalHours: number;
  resetAtTime?: string;
  claimTip: string;
  isPublished: boolean;
  pendingReview: boolean;
  signupBonusText?: string;
}

export const PENDING_CASINOS_BATCH: PendingCasinoData[] = [
  {
    name: "Legendz",
    slug: "legendz",
    siteUrl: "https://legendz.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Baba",
    slug: "baba",
    siteUrl: "https://baba.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Cider",
    slug: "cider",
    siteUrl: "https://cider.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Lavish",
    slug: "lavish",
    siteUrl: "https://lavish.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Betr",
    slug: "betr",
    siteUrl: "https://betr.app",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Luckyland",
    slug: "luckyland",
    siteUrl: "https://luckylandslots.com",
    dailyBonus: "0.30 SC",
    dailyBonusSc: "0.30",
    dailyScAmount: 0.3,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Log in daily and claim bonus from main menu popup",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Splashcoins",
    slug: "splashcoins",
    siteUrl: "https://splashcoins.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Gogogo Gold",
    slug: "gogogo-gold",
    siteUrl: "https://gogogogold.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "BigPirate",
    slug: "bigpirate",
    siteUrl: "https://bigpirate.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Spinsly",
    slug: "spinsly",
    siteUrl: "https://spinsly.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "TurboStakes",
    slug: "turbostakes",
    siteUrl: "https://turbostakes.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Vegas Gems",
    slug: "vegas-gems",
    siteUrl: "https://vegasgems.com",
    dailyBonus: "0.40 SC",
    dailyBonusSc: "0.40",
    dailyScAmount: 0.4,
    minRedemption: "$100 Min Cashout",
    intervalHours: 24,
    claimTip: "Open daily chest in rewards section",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "MoonSpin.US",
    slug: "moonspin-us",
    siteUrl: "https://moonspin.us",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily reload bonus from wallet section",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "RoyalCoins",
    slug: "royalcoins",
    siteUrl: "https://royalcoins.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "BigRoller",
    slug: "bigroller",
    siteUrl: "https://bigroller.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
];

export const additionalPendingCasinos: PendingCasinoData[] = [
  {
    name: "Chumba",
    slug: "chumba",
    siteUrl: "https://chumbacasino.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$100 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from top right menu popup",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Global Poker",
    slug: "global-poker",
    siteUrl: "https://globalpoker.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from lobby notification",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Rolla",
    slug: "rolla",
    siteUrl: "https://rolla.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily reload bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Sixty6",
    slug: "sixty6",
    siteUrl: "https://sixty6.com",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "Coinz.us",
    slug: "coinz-us",
    siteUrl: "https://coinz.us",
    dailyBonus: "1.00 SC",
    dailyBonusSc: "1.00",
    dailyScAmount: 1.0,
    minRedemption: "$50 Min Cashout",
    intervalHours: 24,
    claimTip: "Claim daily bonus from standard lobby",
    isPublished: false,
    pendingReview: true,
  },
  {
    name: "SidePot",
    slug: "sidepot",
    siteUrl: "https://sidepotcasino.com",
    dailyBonus: "0.20 SC (6h Reload)",
    dailyBonusSc: "0.20",
    dailyScAmount: 0.2,
    minRedemption: "$50 Min Cashout",
    intervalHours: 6,
    claimTip: "Claim 0.20 SC reload every 6 hours from promotions tab",
    isPublished: false,
    pendingReview: true,
  },
];

export const ALL_PENDING_CASINOS: PendingCasinoData[] = [
  ...PENDING_CASINOS_BATCH,
  ...additionalPendingCasinos,
];

export const PENDING_CASINOS_MAP: Record<string, PendingCasinoData> = Object.fromEntries(
  ALL_PENDING_CASINOS.map((c) => [c.name.toLowerCase(), c])
);

export function getPendingCasinoByName(name: string): PendingCasinoData | undefined {
  if (!name) return undefined;
  return PENDING_CASINOS_MAP[name.trim().toLowerCase()];
}

